name: "CI" # This name also appears on the badge in README and PyPI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  tox:
    name: Configure test matrix
    runs-on: ubuntu-latest
    outputs:
      envlist: ${{ steps.tox.outputs.envlist }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - name: Install tox and plugins
        run: pip install tox tox-gh-matrix
      - name: Get tox matrix
        id: tox
        run: tox --gh-matrix
      - name: Log saved outputs
        run: echo ${{ steps.tox.outputs.envlist }}

  test:
    name: Test ${{ matrix.tox.name }}
    runs-on: ubuntu-latest
    needs: tox
    strategy:
      fail-fast: false
      matrix:
        tox: ${{ fromJSON(needs.tox.outputs.envlist) }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.tox.python.version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.tox.python.spec }}
        cache: pip
    - name: Install tox
      run: pip install tox
    - name: Test ${{ matrix.tox.name }}
      run: tox -e ${{ matrix.tox.name }}

  release:
    name: Release django-csp
    if: github.event_name == 'release' && github.event.action == 'published'
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies for package building only
        run: pip install build
      - name: Build package for upload to PyPI
        run: python -m build .
      - name: Upload the distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
